blank_issues_enabled: false
contact_links:
<<<<<<< HEAD
  - name: Report model bugs
    url: https://github.com/commaai/openpilot/discussions/categories/model-feedback
    about: Provide feedback for the driving or driver monitoring models
  - name: Discussions
    url: https://github.com/commaai/openpilot/discussions
    about: For questions and general discussion about openpilot
  - name: Community Wiki
    url: https://github.com/commaai/openpilot/wiki
    about: Check out our community wiki
  - name: Community Discord
    url: https://discord.comma.ai
    about: Check out our community discord
=======
  - name: Join the Discord
    url: https://discord.comma.ai
    about: The community Discord is for both openpilot development and experience discussion
  - name: Report model bugs
    url: https://discord.com/channels/469524606043160576/1254834193066623017
    about: Feedback for the driving and driver monitoring models goes in the #driving-feedback in Discord
  - name: Community Wiki
    url: https://github.com/commaai/openpilot/wiki
    about: Check out our community wiki
>>>>>>> 21af6b508f6e06d6f0fcb1b191cbc42514ecf01e
