name: repo maintenance

on:
  schedule:
    - cron: "0 14 * * 1" # every Monday at 2am UTC (6am PST)
  workflow_dispatch:

jobs:
<<<<<<< HEAD
  bump_submodules:
    name: bump_submodules
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    if: github.repository == 'commaai/openpilot'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: bump submodules
      run: |
        git config --global --add safe.directory '*'
        git -c submodule."tinygrad".update=none submodule update --remote
        git add .
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
      with:
        author: Vehicle Researcher <user@comma.ai>
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: bump submodules
        title: '[bot] Bump submodules'
        branch: auto-bump-submodules
        base: master
        delete-branch: true
        body: 'Automatic PR from repo-maintenance -> bump_submodules'
        labels: bot
=======
>>>>>>> 21af6b508f6e06d6f0fcb1b191cbc42514ecf01e
  package_updates:
    name: package_updates
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    if: github.repository == 'commaai/openpilot'
    steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
=======
      with:
        submodules: true
>>>>>>> 21af6b508f6e06d6f0fcb1b191cbc42514ecf01e
    - name: uv lock
      run: |
        python3 -m ensurepip --upgrade
        pip3 install uv
        uv lock --upgrade
<<<<<<< HEAD
=======
    - name: bump submodules
      run: |
        git config --global --add safe.directory '*'
        git -c submodule."tinygrad".update=none submodule update --remote
        git add .
    - name: update car docs
      run: |
        scons -j$(nproc) --minimal opendbc
        PYTHONPATH=. python selfdrive/car/docs.py
        git add docs/CARS.md
>>>>>>> 21af6b508f6e06d6f0fcb1b191cbc42514ecf01e
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
      with:
        author: Vehicle Researcher <user@comma.ai>
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: Update Python packages
        title: '[bot] Update Python packages'
        branch: auto-package-updates
        base: master
        delete-branch: true
        body: 'Automatic PR from repo-maintenance -> package_updates'
        labels: bot
